### ISSUE TITLE
Sign of Zero

### ISSUE THREAD

**Issue by mtesseract** [sharkdp/purescript-format#4]
Hi,
thanks for this package! I stumbled upon the following behaviour:

```
> format (precision 2) 0.0
"-0.00"
```

Is that how purescript-format is supposed to behave? Seems confusing to me.
Thanks,
Moritz

**Comment by sharkdp** [comment]
No, definitely not :smile: 

Thanks for the report.

**Comment by sharkdp** [comment]
This should be fixed in the latest version, thanks again.

**Comment by mtesseract** [comment]
Great, thank you. :-)
